import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Sidebar from "@/components/Sidebar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className="min-h-full flex bg-zinc-50">
        <Sidebar />
        {/* pt-14 offsets the fixed mobile top bar; lg:pt-0 removes it on desktop */}
        <div className="flex-1 min-w-0 pt-14 lg:pt-0">
          {children}
        </div>
      </body>
    </html>
  );
}
